### ISSUE TITLE
Typos and editorial issues

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-numeric-separator#1]
- `999_99_9999L` seems like it has a stray `L` at the end?
- A hex example might be nice
- "only one underscore is allowed" should be "only one consecutive underscore is allowed"
- The "Character" section has some Markdown mishaps by not backticking `_`. I would also suggest using backticks instead of double-quotes to surround the characters.
- "strawnman"

**Comment by domenic** [comment]
- "only between literals (not allowed at the beginning or end of literals)": I think this should be "only between digits"? And does this imply `3_.145` is disallowed?

**Comment by samuelgoto** [comment]
done to all your points.

and yes, that's correct for the last question (3_.145 is disallowed -- starting conservative and adding scope as needed in the future, as opposed to possibly cornering ourselves early on).
