### ISSUE TITLE
Does this affect Number() and parseInt()?

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-numeric-separator#2]

**Comment by samuelgoto** [comment]
Ah, great catch, thanks! I had a note to do that earlier, thanks for catching it!

I'm debating between this: on one side, I'd want the spec to be consistent elsewhere, but on the other side I'd hate to increase scope and couple independent things.

My intuition is that it is a change that won't bring massive deployment compatibility issues, so I think adding/coupling making Number() and parseInt() consistent with the numeric literals is reasonable. 

Done, added to the proposal.
