### ISSUE TITLE
Make sure we cover in a test the unary + conversion

### ISSUE THREAD

**Issue by samuelgoto** [tc39/proposal-numeric-separator#31]
Came up in the review.

We should make sure that ```+ "1_0"``` is converted to ```10``` while using the [unary plus operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_()) (should be because it uses the Number constructor, but we wanted to sanity check).

@rwaldron

**Comment by leobalter** [comment]
IIRC we intentionally set numeric separator to not affect string to number operations to avoid breaking the web. So `+ "1_0"` will consistently evaluate to `NaN` and the separator tokens are only valid within Numeric Literals.
