### ISSUE TITLE
Spec.md disallows multiple separators within a numeric

### ISSUE THREAD

**Issue by TzviPM** [tc39/proposal-numeric-separator#40]
In the readme of this proposal, an example is given for:
```
1_000_000_000           // Ah, so a billion
```

In the spec description here: https://github.com/tc39/proposal-numeric-separator/blob/master/spec.md, however, the diff shows:

```diff
  DecimalDigits ::
    DecimalDigit
+   DecimalDigit NumericLiteralSeparator DecimalDigit
    DecimalDigits DecimalDigit
```

which does not parse the example token.

**Note** Upon further examination, it seems that the spec.html file does have a correct parsing grammar as per the example:

```diff
DecimalDigits ::
    DecimalDigit
-   DecimalDigits DecimalDigit
+   DecimalDigits NumericLiteralSeparator? DecimalDigit
```

**Comment by leobalter** [comment]
Thanks! I updated the spec.md to link directly to the rendered draft.
