### ISSUE TITLE
Add example for binary separators

### ISSUE THREAD

**Issue by TzviPM** [tc39/proposal-numeric-separator#41]
https://github.com/tc39/proposal-numeric-separator#octal-literal mentions that:
> No real benefit with separators here

However, note that binary separators have been added to the proposal here: https://github.com/tc39/proposal-numeric-separator/blob/master/spec.html#L88

**Comment by mathiasbynens** [comment]
The README already has an example for separators within binary integer literals: https://github.com/tc39/proposal-numeric-separator#binary-literals

You also mention the section on octal literals. There’s a separate issue with that, which I’ve filed here: https://github.com/tc39/proposal-numeric-separator/issues/44
