### ISSUE TITLE
On the position of underscores

### ISSUE THREAD

**Issue by Qix-** [tc39/proposal-numeric-separator#9]
Consider the following:

```javascript
const _3 = 4;
console.log(_3);
```

Given this proposal, does the above output `3`? Or `4`?

---

There are _semantic_ consequences of placement. Currently, identifiers cannot start with a number, but allow for an underscore - which directly conflicts with the intent to be backwards compatible.

Any scripts that use identifiers matching `^_[0-9_]+$` would break (in theory). Or, most lexers/parsers would have to become context sensitive.

This might also explain the decision to use a less common delimiter in C++ since the standard mandates `std::bind` allow `std::placeholder` placeholders (e.g. `std::placeholder::_1`, `std::placeholder::_2`, etc), which would cause ambiguous syntax.

---

My more objective opinion is that delimiters can only appear after the first number and before the last number, and can not exceed one at a time. This is in agreement with the first section of the proposal. I figured I'd illustrate _why_ the proposed rules are the most compatible and sensible.

**Comment by ljharb** [comment]
Per https://github.com/samuelgoto/proposal-numeric-separator/issues/4#issuecomment-304384535, this is no longer a situation that can occur.

**Comment by Qix-** [comment]
:+1: Cool, should have kept reading. Thanks!
